_templates_project/_templates_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from temp_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^temp_app/',include('temp_app.urls'))
]

_templates_project/temp_app/urls.py
from django.conf.urls import url
from temp_app import views


urlpatterns = [
    url(r'^other/$',views.other,name='other'),
    url(r'^relative/$',views.relative,name='relative')
]


# TEMPLATE TAGGING:
app_name = 'temp_app'

_templates_project/temp_app/models.py
from django.db import models

# Create your models here.

_templates_project/temp_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict ={'text':'hello world','number':100}
    return render(request,'temp_app/index.html',context_dict)

def other(request):
    return render(request,'temp_app/other.html')

def relative(request):
    return render(request,'temp_app/relative_url_templates.html')

_templates_project/templates/temp_app/base.html
<!DOCTYPE html>
{% load my_extras %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link" href="{% url 'temp_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      <!-- Anything outside of this block will be inherited
      if you extend! -->
      {% endblock %}

    </div>

  </body>
</html>

_templates_project/templates/temp_app/index.html
<!DOCTYPE html>

{% extends "temp_app/base.html" %}

  {% block body_block %}

    <h1>Welcome to index.html</h1>
    <h1>This is temp_app's homepage</h1>

    <p></p>

    <h3><a href="{% url 'temp_app:relative' %}">Click</a> for relative</h3>
    <h3><a href="{% url 'temp_app:other' %}">Click</a> for other</h3>
    <p></p>

    <h5>{{ text|cut:'world' }}</h5>

    <h5>{{ number|add:"99" }}</h5>

    {% endblock %}

  </body>
</html>

_templates_project/templates/temp_app/other.html
<!DOCTYPE html>

{% extends "temp_app/base.html" %}

  {% block body_block %}
    <h1>Welcome to other.html</h1>
    <p></p>
    <h3>This is an example of template inheritance!</h3>
  {% endblock %}

  </body>
</html>

_templates_project/templates/temp_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Relative URL Templates</title>
  </head>
  <body>

    <h1>Welcome to relative url templates.html</h1>

    <h3><a href="{% url 'temp_app:other' %}">Click</a> to visit other.html</h3>
    <p></p>
    <a href="{% url 'admin:index' %}">admin</a>
    <p></p>
    <a href="{% url 'index' %}">Back to homepage</a>

  </body>
</html>